name: Release native Linux Packages

on:
  workflow_call:
    inputs:
      amdgpu_family:
        description: gfx arch for creating the s3 bucket url
        required: true
        type: string
      artifact_run_id:
        description: workflow run id to download the artifacts from
        type: string
      rocm_version:
        description: ROCm version to append to the package( Like 8.0.0 or 8.1.0).
        required: true
        type: string
      package_type:
        description: Specify whether debian or rpm packages are needed (deb or rpm).
        required: true
        type: string
      package_suffix:
        description: The suffix to be added to package name(build_no or master or rc or combiantion).
        required: true
        type: string
  workflow_dispatch:
    inputs:
      amdgpu_family:
        type: choice
        options:
          - gfx110X-dgpu
          - gfx1151
          - gfx120X-all
          - gfx94X-dcgpu
          - gfx950-dcgpu
        default: gfx94X-dcgpu
      artifact_run_id:
        description: workflow run id to download the artifacts from
        type: string
        default: "17840675558"
      output_dest_dir:
        description: Local folder name where the created packages will be saved
        type: string
        default: "PACKAGE_DIST_DIR"
      rocm_version:
        description: ROCm version to append to the package( Like 7.0.0 or 7.1.0)
        type: string
        default: "7.9.0"
      package_type:
        description: Specify whether debian or rpm packages are needed (deb or rpm).
        required: true
        type: choice
        options:
          - rpm
          - deb
        default: "rpm"
      package_suffix:
        description: The suffix to be added to package name(build_no or master or rc or combiantion).
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Release Native Linux Package (xfail ${{ inputs.expect_failure }}) 
    strategy:
      fail-fast: false

    uses: ./.github/workflows/build_native_linux_packages.yml
    with:
      amdgpu_family: ${{ inputs.amdgpu_family }}
      artifact_run_id: ${{ inputs.artifact_run_id }}
      rocm_version: ${{ inputs.rocm_version }}
      package_type: ${{ inputs.package_type }}
      package_suffix: ${{ inputs.package_suffix }}
